### PR TITLE
refactor nio write

### PR DESCRIPTION
**Pull request by Hailei**
refactor nio write  inspire from netty.Note that this is a conceptual demo,maybe can't run

### CODE REVIEW

**Comment by HeartSaVioR** [comment]
@Hailei Thanks for your effort!
Btw, could you rewrite your PR to respect indentation?
(Actually it's hard to find changeset because github diff shows all things to changeset.)
Jedis uses Eclipse IDE's Java convention (built-in) formatter.

**Comment by Hailei** [comment]
following is my eclipse built-in format
format
Using git diff  still have some different. 
git_diff

**Comment by HeartSaVioR** [comment]
@Hailei Jedis uses "Java Convention".
Sorry, "Eclipse" mean that only Eclipse can support this convention.

**Comment by Hailei** [comment]
@HeartSaVioR  Pardon me for my carelessness.

**Comment by HeartSaVioR** [comment]
@Hailei Oh, it's trivial so please don't mind. I've learned many things from you. 
Keep up the good work together!

**Comment by HeartSaVioR** [comment]
Unfortunately, we don't seem to adopt async for now. Closing.

**Pull request closed without merging**
